FROM docker.io/library/node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY sql ./sql
COPY src ./src
COPY public ./public

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

CMD ["node", "src/server.js"]
